### ISSUE TITLE
PURE proposal: supply chain security

### ISSUE THREAD

**Issue by trishankatdatadog** [uptane/pures#2]
Basically, talking about how we can extend Uptane 2.0.0 with in-toto for supply chain security. It would be largely based on [ITE-2](https://github.com/in-toto/ITE/blob/master/ITE/2/README.adoc) and [ITE-3](https://github.com/in-toto/ITE/blob/master/ITE/3/README.adoc).

Cc @mnm678

**Comment by trishankatdatadog** [comment]
cc @jhdalek55

**Comment by tkfu** [comment]
I mentioned this concern in the 21.09.14 Uptane call, but I'll just reiterate it here: I think it will be really important to consider the extra data transfer this will incur. Let me give a couple of examples of why that is:

* For some non-automotive IoT applications, manufacturers end up choosing very-low-bandwidth modems like LTE Cat M. (Real-world speeds typically around 300kbps (~60kB/s), and often getting as low as 40-60 kbps (~5-7 kB/s).) There can be various reasons for this choice, from low power consumption to the fact that you can stick a Cat M modem on a module or carrier board and have it work in most any region around the world, instead of having to manufacture per-region variants. If in-toto metadata is on the order of dozens or hundreds of kB per target and it gets downloaded every time targets metadata is updated, that would be much too large a burden to bear on those connections.
* Even with higher bandwidth options, data volume can be quite expensive, and automotive OEMs (more in NA than in EMEA) tend to be incredibly price-sensitive to any kind of recurring data. If, for example, we end up with a proposal such that in-toto metadata gets fetched for every target in the image repo targets metadata every time that metadata is refreshed, it could easily add up to a lot of data very quickly.

We probably only need to fetch this data when a vehicle is directed to install a specific target, though, and only for the target(s) being installed at the moment. I think as long as that's the case the extra data volume probably won't matter nearly as much.

**Comment by jhdalek55** [comment]
Note that work on this PURE will likely begin this spring.  It will be the second step after the whitepaper is released.

**Comment by adityasaky** [comment]
https://github.com/uptane/pures/pull/9

There's an early draft discussing Scudo now.

**Comment by jhdalek55** [comment]
A draft of Scudo is now being put forth for acceptance. Please review,. comment, and vote on approval at https://github.com/uptane/pures/pull/9.

**Comment by JustinCappos** [comment]
Resolved with the merge of #9 !
